import Head from "next/head";
import { AudioPlayer } from "@/modules/AudioPlayer/containers/AudioPlayer";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Flex, Loader } from "@/ui";

export default function Home() {
  const [txid, setTxid] = useState<string>();
  const router = useRouter();

  useEffect(() => {
    // console.log(router.query.tx);

    if (router.query.tx) {
      setTxid(router.query.tx as string);
    } else {
      console.log("No txid provided");
    }
  }, [router.query.tx]);

  return (
    <>
      <Head>
        <title>AR-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Flex
        css={{
          height: "100%",
        }}
        align="center"
        justify="center"
      >
        {txid ? <AudioPlayer txid={txid} /> : <Loader />}
      </Flex>
    </>
  );
}
